# Generated by Django 6.0.3 on 2026-04-28 20:59

import MessedUpSite.apps.registrationlists.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("activities", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistrationList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("description", models.TextField()),
                ("deadline", models.DateTimeField()),
                (
                    "linked_activity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="activities.activity",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=255)),
                (
                    "type",
                    MessedUpSite.apps.registrationlists.fields.QuestionField(
                        choices=(
                            ("char", "Short Text"),
                            ("text", "Long Text"),
                            ("datetime", "Date & Time"),
                            ("bool", "True/False"),
                            ("int", "Number"),
                            ("email", "Email"),
                        ),
                        max_length=20,
                    ),
                ),
                ("mandatory", models.BooleanField(default=False)),
                (
                    "registration_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="registrationlists.registrationlist",
                    ),
                ),
            ],
        ),
    ]
