# Generated by Django 6.0.3 on 2026-04-27 13:35

import MessedUpSite.apps.registrationlists.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RegistrationList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "linked_activity",
                    MessedUpSite.apps.registrationlists.fields.ActivityField(
                        choices=((1, "Kick-In"), (2, "Munster")), max_length=50
                    ),
                ),
                ("list_title", models.CharField()),
                ("description", models.TextField()),
                (
                    "questions",
                    MessedUpSite.apps.registrationlists.fields.QuestionField(),
                ),
                ("deadline", models.DateTimeField()),
                ("organizer", models.CharField()),
            ],
        ),
    ]
