# Generated by Django 6.0.3 on 2026-04-27 14:53

import MessedUpSite.apps.registrationlists.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registrationlists", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="registrationlist",
            name="list_title",
        ),
        migrations.RemoveField(
            model_name="registrationlist",
            name="organizer",
        ),
        migrations.AlterField(
            model_name="registrationlist",
            name="linked_activity",
            field=MessedUpSite.apps.registrationlists.fields.ActivityField(
                choices=((1, "Kick-In"), (2, "Munster"))
            ),
        ),
    ]
