# Generated by Django 6.0.3 on 2026-04-27 15:42

import MessedUpSite.apps.registrationlists.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrationlists", "0002_remove_registrationlist_list_title_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="registrationlist",
            name="questions",
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=255)),
                (
                    "type",
                    MessedUpSite.apps.registrationlists.fields.QuestionField(
                        choices=(
                            ("char", "Short Text"),
                            ("text", "Long Text"),
                            ("datetime", "Date & Time"),
                            ("bool", "True/False"),
                            ("int", "Number"),
                            ("email", "Email"),
                        ),
                        max_length=20,
                    ),
                ),
                (
                    "registration_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="registrationlists.registrationlist",
                    ),
                ),
            ],
        ),
    ]
