# Generated by Django 6.0.3 on 2026-04-27 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrationlists", "0003_remove_registrationlist_questions_question"),
    ]

    operations = [
        migrations.RenameField(
            model_name="question",
            old_name="text",
            new_name="question",
        ),
        migrations.AddField(
            model_name="question",
            name="mandatory",
            field=models.BooleanField(default=False),
        ),
    ]
