# Generated by Django 6.0.3 on 2026-04-28 20:59

import MessedUpSite.apps.activities.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "type",
                    MessedUpSite.apps.activities.fields.ActivityTypeField(
                        choices=(
                            ("activity", "Activity"),
                            ("tournament", "Tournament"),
                            ("poll", "Poll"),
                        ),
                        max_length=50,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        default="/MessedUpSite/static/assets/Images/Logo Light.png",
                        upload_to="MessedUpSite/static/activity_images",
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=100)),
                ("description", models.TextField()),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("location", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "organizer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.userpersona",
                    ),
                ),
            ],
            options={
                "ordering": ["created", "is_active"],
            },
        ),
    ]
