# Generated by Django 6.0.3 on 2026-04-23 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="image",
            field=models.ImageField(blank=True, default="", upload_to=""),
        ),
        migrations.AddField(
            model_name="activity",
            name="type",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]
