# Generated by Django 6.0.3 on 2026-04-23 13:31

import MessedUpSite.apps.activities.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0002_activity_image_activity_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="type",
            field=MessedUpSite.apps.activities.fields.ActivityTypeField(
                choices=(
                    ("activity", "Activity"),
                    ("tournament", "Tournament"),
                    ("poll", "Poll"),
                ),
                max_length=50,
            ),
        ),
    ]
