# Generated by Django 6.0.3 on 2026-04-27 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0004_alter_activity_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="image",
            field=models.ImageField(
                blank=True,
                default="/MessedUpSite/static/assets/Images/Logo Light.png",
                upload_to="MessedUpSite/static/activity_images",
            ),
        ),
    ]
