# Generated by Django 6.0.3 on 2026-04-27 13:35

import MessedUpSite.apps.activities.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0005_alter_activity_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="activity",
            name="organizer",
            field=MessedUpSite.apps.activities.fields.OrganizerField(
                choices=(), max_length=50
            ),
        ),
    ]
