# Generated by Django 6.0.3 on 2026-04-29 17:27

import MessedUpSite.apps.documents.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "type",
                    MessedUpSite.apps.documents.fields.DocumentTypeField(
                        choices=(
                            ("gma", "GMA"),
                            ("legal", "Legal"),
                            ("other", "Other"),
                        ),
                        default="other",
                        max_length=50,
                    ),
                ),
                (
                    "language",
                    MessedUpSite.apps.documents.fields.DocumentLanguageField(
                        choices=(("nl", "Dutch"), ("en", "English")),
                        default="en",
                        max_length=2,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, default="", max_length=100, unique=True
                    ),
                ),
                ("file", models.FileField(upload_to="MessedUpSite/static/documents")),
                ("priority", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["created"],
            },
        ),
    ]
