# Generated by Django 6.0.3 on 2026-04-25 16:13

import MessedUpSite.apps.documents.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="type",
            field=MessedUpSite.apps.documents.fields.DocumentTypeField(
                choices=(("gma", "GMA"), ("other", "Other")),
                default="other",
                max_length=50,
            ),
        ),
    ]
