# Generated by Django 6.0.3 on 2026-04-25 16:57

import MessedUpSite.apps.documents.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_document_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="language",
            field=MessedUpSite.apps.documents.fields.DocumentLanguageField(
                choices=(("nl", "Dutch"), ("en", "English")), default="en", max_length=2
            ),
        ),
    ]
