# Generated by Django 6.0.3 on 2026-04-25 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0003_document_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="title",
            field=models.CharField(blank=True, default="", max_length=100, unique=True),
        ),
    ]
