# Generated by Django 6.0.3 on 2026-04-25 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0004_alter_document_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="priority",
            field=models.IntegerField(default=0),
        ),
    ]
