# Generated by Django 6.0.3 on 2026-04-25 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activityapi", "0003_alter_activity_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="image",
            field=models.ImageField(
                blank=True, default="", upload_to="MessedUpSite/static/activity_images"
            ),
        ),
    ]
